language: python
python:
  - "3.5"
#
before_install:
  - echo $SSH_KEY | base64 --decode > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - git config --global user.name "小饼"
  - git config --global user.email i@iloxe.com

# command to run tests
script: python ./run.py

after_success:
  - git add .
  - git commit -m "push Novel"
  - git push -f git@github.com:Loxe/GetTxtPython.git HEAD:master
  